import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  allSidebar: [{ type: "autogenerated", dirName: "topics" }],
  ifrSidebar: [{ type: "autogenerated", dirName: "topics/ifr" }],
  cfiSidebar: [{ type: "autogenerated", dirName: "cfi" }],
  deepDiveSidebar: [{ type: "autogenerated", dirName: "dives" }],
};

export default sidebars;
